# SHARKNO Frontend Deployment for AWS EKS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharkno-frontend
  namespace: sharkno
  labels:
    app: sharkno-frontend
    version: v1
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: sharkno-frontend
  template:
    metadata:
      labels:
        app: sharkno-frontend
        version: v1
    spec:
      containers:
      - name: sharkno-frontend
        image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/sharkno/frontend:latest
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "512Mi"
          limits:
            memory: "256Mi"
            cpu: "200m"
            ephemeral-storage: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101 # nginx user
          runAsGroup: 101
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false

---
apiVersion: v1
kind: Service
metadata:
  name: sharkno-frontend-service
  namespace: sharkno
  labels:
    app: sharkno-frontend
spec:
  selector:
    app: sharkno-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sharkno-frontend-hpa
  namespace: sharkno
  labels:
    app: sharkno-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sharkno-frontend
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      selectPolicy: Max